# These are supported funding model platforms

github: EndemicMedia
patreon: # Replace with a Patreon username
open_collective: # Replace with an Open Collective username
ko_fi: # Replace with a Ko-fi username
tidelift: # Replace with a Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a Liberapay username
issuehunt: # Replace with an IssueHunt username
otechie: # Replace with an Otechie username
lfx_crowdfunding: # Replace with a LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://github.com/sponsors/EndemicMedia']
