name: ClaudeCoderAction
description: 'Process pull requests using AWS Bedrock and Claude 3.7 Sonnet to suggest code changes'
branding:
  icon: "cpu"
  color: orange
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: false
    default: 'us-east-1'
  max-tokens:
    description: 'Maximum number of tokens for Claude to generate (up to 128K)'
    required: false
    default: '64000'
  max-requests:
    description: 'Maximum number of requests to make to AWS Bedrock'
    required: false
    default: '10'
  enable-thinking:
    description: 'Enable Claude''s extended thinking capability (true/false)'
    required: false
    default: 'true'
  thinking-budget:
    description: 'Token budget for Claude''s thinking process (minimum: 1024)'
    required: false
    default: '1024'
  extended-output:
    description: 'Enable 128K extended output capability (true/false)'
    required: false
    default: 'true'
  request-timeout:
    description: 'API request timeout in milliseconds'
    required: false
    default: '3600000'
runs:
  using: "node20"
  main: "dist/index.js"