name: ClaudeCoder
on:
  pull_request:
    types: [opened, edited]
    branches:
      - '!main'
  pull_request_review_comment:
    types: [created, edited]
    branches:
      - '!main'
  issue_comment:
    types: [created, edited]

jobs:
  process-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'issue_comment' || (github.event_name == 'issue_comment' && github.event.issue.pull_request) }}
    steps:
    - uses: actions/checkout@v3
    - name: ClaudeCoderAction
      uses: EndemicMedia/claudecoder@v1.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
